- name: Create Release
  id: create_release
  uses: actions/create-release@v1
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    tag_name: v1
    release_name: RF Bot Release
    draft: false
    prerelease: false

- name: Upload EXE to Release
  uses: actions/upload-release-asset@v1
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    upload_url: ${{ steps.create_release.outputs.upload_url }}
    asset_path: ./publish/bot.exe
    asset_name: bot.exe
    asset_content_type: application/octet-stream
